"""
Report Writer Agent
Creates comprehensive, well-structured research reports
"""

from typing import Dict, List, Optional
from langchain_openai import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage
from datetime import datetime
import re


class ReportWriter:
    """Agent chuyên tạo báo cáo nghiên cứu chuyên nghiệp"""
    
    def __init__(self, api_key: str, model: str = "gpt-4-turbo-preview"):
        self.llm = ChatOpenAI(
            model=model,
            temperature=0.7,
            api_key=api_key
        )
    
    def create_full_report(self,
                          topic: str,
                          research_findings: str,
                          analysis: Dict,
                          sources: List[Dict],
                          style: str = "academic") -> str:
        """Tạo báo cáo hoàn chỉnh"""
        
        # Generate each section
        executive_summary = self._create_executive_summary(topic, research_findings, analysis)
        introduction = self._create_introduction(topic)
        main_body = self._create_main_body(research_findings, analysis)
        conclusions = self._create_conclusions(topic, analysis)
        references = self._create_references(sources)
        
        # Combine all sections
        report = f"""# Research Report: {topic}

**Date:** {datetime.now().strftime("%B %d, %Y")}
**Generated by:** AI Research Assistant

---

## Executive Summary

{executive_summary}

---

## 1. Introduction

{introduction}

---

## 2. Research Findings

{main_body}

---

## 3. Analysis & Insights

{analysis.get('insights', 'Analysis not available')}

---

## 4. Conclusions

{conclusions}

---

## 5. References

{references}

---

## Appendix

### Research Statistics
- **Total Sources Analyzed:** {len(sources)}
- **Research Depth:** Comprehensive multi-source analysis
- **Date of Research:** {datetime.now().strftime("%Y-%m-%d")}

"""
        
        return self._apply_style(report, style)
    
    def _create_executive_summary(self, topic: str, findings: str, analysis: Dict) -> str:
        """Tạo executive summary"""
        
        prompt = f"""Create a concise executive summary for a research report on "{topic}".

Key Findings:
{findings[:1000]}

Analysis:
{str(analysis)[:500]}

The executive summary should:
- Be 150-200 words
- Highlight the most important findings
- Present key conclusions
- Be accessible to non-experts

Write in a professional, clear style.
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are an expert at writing clear, impactful executive summaries."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _create_introduction(self, topic: str) -> str:
        """Tạo introduction section"""
        
        prompt = f"""Write an introduction for a research report on "{topic}".

The introduction should:
1. Provide context and background
2. Explain why this topic is important
3. Outline what the report will cover
4. State the research objectives

Length: 200-300 words
Style: Professional and engaging
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are skilled at writing engaging research introductions."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _create_main_body(self, findings: str, analysis: Dict) -> str:
        """Tạo main body của report"""
        
        prompt = f"""Organize these research findings into a well-structured main body:

Findings:
{findings}

Create subsections covering:
1. Key Facts and Data
2. Current State of Knowledge
3. Recent Developments
4. Expert Perspectives
5. Emerging Trends

Use clear headings and maintain logical flow.
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are expert at organizing research findings into clear, logical sections."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _create_conclusions(self, topic: str, analysis: Dict) -> str:
        """Tạo conclusions section"""
        
        prompt = f"""Write conclusions for a research report on "{topic}".

Analysis Results:
{str(analysis)[:800]}

The conclusions should:
1. Summarize key findings
2. Present main insights
3. Discuss implications
4. Suggest areas for future research
5. Provide actionable takeaways

Length: 250-350 words
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You excel at drawing meaningful conclusions from research."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _create_references(self, sources: List[Dict]) -> str:
        """Tạo references section với proper citations"""
        
        references = []
        
        for i, source in enumerate(sources, 1):
            if not source.get('success'):
                continue
            
            # Create citation
            title = source.get('title', 'Untitled')
            url = source.get('url', '')
            authors = source.get('authors', [])
            date = source.get('publish_date', 'n.d.')
            
            # Format author
            if authors and len(authors) > 0:
                author_str = ', '.join(authors[:3])
                if len(authors) > 3:
                    author_str += ', et al.'
            else:
                # Extract from URL
                author_str = self._extract_source_from_url(url)
            
            # Format date
            if hasattr(date, 'strftime'):
                date_str = date.strftime('%Y, %B %d')
            else:
                date_str = str(date) if date else 'n.d.'
            
            citation = f"{i}. {author_str}. ({date_str}). *{title}*. Retrieved from {url}"
            references.append(citation)
        
        if not references:
            return "No sources available."
        
        return '\n\n'.join(references)
    
    def create_summary(self, report: str, length: str = "medium") -> str:
        """Tạo summary của report với độ dài khác nhau"""
        
        word_limits = {
            "short": 100,
            "medium": 250,
            "long": 500
        }
        
        limit = word_limits.get(length, 250)
        
        prompt = f"""Create a {length} summary of this research report (approximately {limit} words):

{report}

Focus on the most important findings and conclusions.
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are expert at creating concise, informative summaries."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def create_blog_post(self, topic: str, research_data: str) -> str:
        """Chuyển research thành blog post"""
        
        prompt = f"""Convert this research into an engaging blog post about "{topic}":

{research_data[:2000]}

The blog post should:
- Have a catchy title
- Be conversational and engaging
- Include relevant examples
- Be accessible to general readers
- End with key takeaways

Length: 600-800 words
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are a skilled content writer who makes complex topics accessible."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def create_presentation_outline(self, report: str) -> str:
        """Tạo outline cho presentation từ report"""
        
        prompt = f"""Create a presentation outline from this research report:

{report[:1500]}

Format:
- Slide 1: Title & Overview
- Slides 2-3: Background & Context  
- Slides 4-7: Key Findings (one per slide)
- Slide 8: Analysis & Insights
- Slide 9: Conclusions
- Slide 10: Q&A

Include talking points for each slide.
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are expert at creating effective presentation outlines."),
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _apply_style(self, report: str, style: str) -> str:
        """Áp dụng style cụ thể cho report"""
        
        if style == "academic":
            return report  # Already in academic style
        
        elif style == "business":
            prompt = f"""Rewrite this report in a business-focused style:
- More concise
- Focus on actionable insights
- Use business terminology
- Add executive focus

Original:
{report}
"""
        
        elif style == "casual":
            prompt = f"""Rewrite this report in a casual, accessible style:
- Conversational tone
- Simpler language
- More examples
- Less formal structure

Original:
{report}
"""
        else:
            return report
        
        response = self.llm.invoke([
            HumanMessage(content=prompt)
        ])
        
        return response.content
    
    def _extract_source_from_url(self, url: str) -> str:
        """Extract source name from URL"""
        try:
            # Extract domain
            domain = re.search(r'https?://(?:www\.)?([^/]+)', url)
            if domain:
                source = domain.group(1).split('.')[0]
                return source.capitalize()
        except:
            pass
        return "Unknown Source"
    
    def add_visual_elements_suggestions(self, report: str) -> Dict:
        """Đề xuất các visual elements cho report"""
        
        prompt = f"""Suggest visual elements (charts, graphs, diagrams) for this report:

{report[:1000]}

For each suggestion, specify:
- Type of visual (chart, graph, diagram, etc.)
- What data to visualize
- Purpose and insight it would provide

Suggest 3-5 visuals.
"""
        
        response = self.llm.invoke([
            SystemMessage(content="You are expert at data visualization planning."),
            HumanMessage(content=prompt)
        ])
        
        return {
            "suggestions": response.content,
            "count": len(response.content.split('\n\n'))
        }